image: python:2

stages:
  - test

acceptance tests:
  stage: test
  before_script:
    - pip install fabric==1.14.1
    - cp $CS_CONF $HOME/.cloudsigma.conf
    - grep -e api_endpoint -e username -e drive_name $HOME/.cloudsigma.conf
    - python setup.py install
    - pip freeze
  script:
    - nosetests ./src/testing/acceptance/test_accounts.py
    - nosetests ./src/testing/acceptance/test_billing.py
    - nosetests ./src/testing/acceptance/test_capabilities.py
    - nosetests ./src/testing/acceptance/test_core.py
    - nosetests ./src/testing/acceptance/test_drives.py
    - nosetests ./src/testing/acceptance/test_firewall.py
    - nosetests ./src/testing/acceptance/test_networking.py
    - nosetests ./src/testing/acceptance/test_profile.py
    - nosetests ./src/testing/acceptance/test_servers.py
    - nosetests ./src/testing/acceptance/test_snapshots.py
    - nosetests ./src/testing/acceptance/test_subscriptions.py
    - nosetests ./src/testing/acceptance/test_tags.py
    - nosetests ./src/testing/acceptance/test_websocket.py

