image: python:2

stages:
  - test

acceptance tests:
  stage: test
  before_script:
    - cp $CS_CONF $HOME/.cloudsigma.conf
    - grep -e api_endpoint -e username -e drive_name $HOME/.cloudsigma.conf
    - python setup.py install
  script:
    - nosetests

